require('jquery')
require('./js/jquery-multiselect')
require('./js/jquery.mask.min')
require('./sass/main.scss')
require('./js/FSS')
require('./js/polygon-app')
require('./js/home');
require('./img/icon_sajic.jpg')
require('./js/firebase') 
